flyway:
  baseline-on-migrate: true
logging:
  level:
    org:
      hibernate:
        sql: DEBUG
      springframework:
        web: DEBUG
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    max-active: 10
    max-idle: 8
    max-wait: 10000
    min-evictable-idle-time-millis: 1000
    min-idle: 8
    password: 123456
    time-between-eviction-runs-millis: 1
    url: jdbc:mysql://localhost:3306/test
    username: root
  devtools:
    restart:
      enabled: true
      exclude: public/**
  jpa:
    database: MYSQL
    hibernate:
      ddl-auto: update
    show-sql: true
